version: '3'
services:
    my-nginx:
        container_name: my-nginx
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./www:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - my-php
        restart: always
    my-php:
        container_name: my-php
        build: ./php
        volumes:
            - ./www:/usr/share/nginx/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/logs:/usr/local/var/log
        restart: always